apiVersion: v1
kind: ConfigMap
metadata:
  name: arb-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_FLYWAY_ENABLED: "false"
  
  PRIMARY_DATABASE_URL: "jdbc:postgresql://postgres-service:5432/my_db"
  PRIMARY_DATABASE_HOST: "postgres-service"
  PRIMARY_DATABASE_NAME: "my_db"
  PRIMARY_DATABASE_PORT: "5432"
  
  REPLICA_DATABASE_URL: "jdbc:postgresql://postgres-service:5432/my_db"
  REPLICA_DATABASE_HOST: "postgres-service"
  REPLICA_DATABASE_NAME: "my_db"
  REPLICA_DATABASE_PORT: "5432"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: arb-secrets
type: Opaque
data:
  PRIMARY_DATABASE_USERNAME: 
  PRIMARY_DATABASE_PASSWORD: 
  
  REPLICA_DATABASE_USERNAME: 
  REPLICA_DATABASE_PASSWORD: 
  
  JWT_SECRET: 
  COINMARKETCAP_API_KEY: 
