apiVersion: batch/v1
kind: Job
metadata:
  name: arb-flyway-migration
spec:
  template:
    metadata:
      labels:
        app: flyway-migrator
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
      - name: flyway
        image: andrii7/crypto-arb-flyway:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            flyway -url=jdbc:postgresql://${PRIMARY_DATABASE_HOST}:$(PRIMARY_DATABASE_PORT)/$(PRIMARY_DATABASE_NAME) \
                   -user=$(PRIMARY_DATABASE_USERNAME) \
                   -password=$(PRIMARY_DATABASE_PASSWORD) \
                   -connectRetries=60 \
                   migrate
        envFrom:
        - configMapRef:
            name: arb-config
        - secretRef:
            name: arb-secrets
      
      restartPolicy: OnFailure
